services:
  web:
    image: devopsdz83/my-devops-app:latest 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    ports:
      - "4000:4000"
    volumes:
      - .:/redis
      # يربط البورت 5000 تاع الحاوية مع بورت الجهاز.
    environment:
    - REDIS_URL=redis://redis:6379 # هذا هو عنوان Redis داخل الحاوية
    depends_on:
      - redis-machine
    networks:
      - public-network
  # يعني Flask مايخدمش حتى Redis يكون واجد.
  redis-machine:
    # تعريف خدمة Redis.
    # image: redis:alpine
    # image: redis/redisinsight:latest
    image: redis/redis-stack
    # نستعمل صورة خفيفة تاع Redis مبنية على Alpine.
    ports:
      - "6379:6379"
      - "8000:8001"
    networks:
      - public-network
networks:
  public-network:
    driver: bridge 