apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: devopsdz83/my-devops-app:latest 
        ports:
        - containerPort: 4000
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: flask-config
              key: redis_url
        - name : admin_password
          valueFrom:
            secretKeyRef:
              name: flask-secret
              key: admin_password