name: CI/CD with Docker Hub and EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-devops-app .

      - name: Push image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-devops-app

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > devopsdz_key.pem
          chmod 400 devopsdz_key.pem

      - name: Deploy on EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i devopsdz_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-devops-app
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 5000:5000 --name my-app ${{ secrets.DOCKER_USERNAME }}/my-devops-app
          EOF
