name: Deploy to EC2

on:
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Connect and Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: |
            cd my-devops-app
            git pull origin main
            docker compose down
            docker compose up -d --build

